#
# Dependabot configuration file
#

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    ignore:
      # progenitor is managed by .github/workflows/integrate.yml
      - dependency-name: "progenitor"
      - dependency-name: "progenitor-client"
