- name: Install perl-IPC-Cmd on manylinux
  if: contains(matrix.container.image, 'manylinux')
  run: |
    yum install -y perl-IPC-Cmd musl-tools
    git config --global --add safe.directory /__w/oxide.rs/oxide.rs
