- name: Install perl-IPC-Cmd on manylinux
  if: contains(matrix.container.image, 'manylinux')
  run: |
    yum install -y perl-IPC-Cmd
    git config --global --add safe.directory /__w/oxide.rs/oxide.rs
- name: Install musl-tools
  if: contains(matrix.container.image, 'manylinux')
  run: |
    yum install -y musl-tools
