# Reflector configuration (oxidecompuer/reflector)

# When any of the listeners configured below activate, run .github/workflows/integate.yml targeting main

workflow = "integrate.yml"
branch = "main"

# Listen for pushes to the nexus.json file in oxidecomputer/omicron and multiple source paths in
# oxidecomputer/progenitor (on each repository's respective default branch).

[[on]]
repository = "oxidecomputer/omicron"
paths = [
  "openapi/nexus.json",
]

[[on]]
repository = "oxidecomputer/progenitor"
paths = [
  "progenitor-client/**",
  "progenitor-impl/**",
  "progenitor-macro/**",
  "progenitor/**",
  "Cargo.toml",
  "Cargo.lock"
]
