# Reflector configuration (oxidecompuer/reflector)

# When any of the listeners configured below activate, run .github/workflows/integate.yml targeting main

workflow = "integrate.yml"
branch = "main"

# Request an installation token when running this workflow

requires_token = true

# Listen for pushes to the nexus.json file in oxidecomputer/omicron and multiple source paths in
# oxidecomputer/progenitor (on each repository's respective default branch).

[[on]]
repository = "oxidecomputer/omicron"
paths = [
  "openapi/nexus.json",
]

[[on]]
repository = "oxidecomputer/progenitor"
paths = [
  "progenitor-client/**",
  "progenitor-impl/**",
  "progenitor-macro/**",
  "progenitor/**",
  "Cargo.toml",
  "Cargo.lock"
]

# Listen for changes on the repo's own main branch. This ensures that the integration  branch is
# always built on top of the latest code. Actions triggered by this location are run with a
# 5 minute delay. This allows for multiple pushes to the main branch to be batched together into
# a single run.
[[on]]
repository = "oxidecomputer/oxide.rs"
paths = [
  "**",
]
debounce = 300